/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * FindBlockVoronoi3D.java
 *
 * Created on 15-giu-2010, 8.52.30
 */
package Tough2ViewerPRJ;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author stebond
 */
public class AdvancedBlockSelection3D extends javax.swing.JFrame {

    /**
     * Creates new form FindBlockVoronoi3D
     */
    public AdvancedBlockSelection3D() {
        initComponents();
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        String[] blockname = new String[nxyz];
        for (int i_b = 0; i_b < nxyz; i_b = i_b + 1) {
            blockname[i_b] = Tough2Viewer.dataobj.get_BlockName(i_b);
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(blockname));
        jSurfaceSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames2()));
        jSurfaceSelectorComboBoxTOP.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames2()));
        jSurfaceSelectorComboBoxBOTTOM.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames2()));
        jLabel6.setText("    ");
        jLabel8.setText("    ");
        jLabel10.setText("    ");
        jLabel12.setText("    ");
        jLabel14.setText("    ");
        jRockTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_RockType_name_str()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddRemoveButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jAddOneBlock = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRockTypeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jAddRockTypeButton = new javax.swing.JButton();
        jRockButtonRemoveButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jAboveBelowComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSurfaceSelectorComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jAddBlockSurfaceButton = new javax.swing.JButton();
        jRemoveBlockSurfaceButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jIN_OUT_ComboBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jSurfaceSelectorComboBoxTOP = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jSurfaceSelectorComboBoxBOTTOM = new javax.swing.JComboBox<>();
        jAddBlockSurfaceButton1 = new javax.swing.JButton();
        jRemoveBlockSurfaceButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxSameX = new javax.swing.JCheckBox();
        jCheckBoxSameY = new javax.swing.JCheckBox();
        jCheckBoxSameZ = new javax.swing.JCheckBox();
        jRadioButtonPickAdd = new javax.swing.JRadioButton();
        jRadioButtonPickRemove = new javax.swing.JRadioButton();
        jCheckBoxPickSameXY = new javax.swing.JCheckBox();
        jCheckBoxPickSameXZ = new javax.swing.JCheckBox();
        jCheckBoxSameYZ = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jSelectAllVisibleBlocks = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AdvancedBlockSelection");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Block Selection")));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setText("AAAAA");

        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jAddOneBlock.setText("Add");
        jAddOneBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddOneBlockActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Block information"));

        jLabel9.setText("Yo=");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Label10");

        jLabel7.setText("Xo=");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("label8");

        jLabel13.setText("Rocktype=");

        jLabel11.setText("Zo=");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("label12");

        jLabel5.setText("BlockName=");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("label14");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Label6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jAddOneBlock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jAddOneBlock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("RockType Selector"));

        jRockTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Select Rocktype");

        jAddRockTypeButton.setText("Add");
        jAddRockTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddRockTypeButtonActionPerformed(evt);
            }
        });

        jRockButtonRemoveButton.setText("Remove");
        jRockButtonRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRockButtonRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRockTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddRockTypeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRockButtonRemoveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRockTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jAddRockTypeButton)
                    .addComponent(jRockButtonRemoveButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Surface Selector"));

        jAboveBelowComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Above", "Below" }));

        jLabel2.setText("Select blocks that are");

        jSurfaceSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("the surface");

        jAddBlockSurfaceButton.setText("Add");
        jAddBlockSurfaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBlockSurfaceButtonActionPerformed(evt);
            }
        });

        jRemoveBlockSurfaceButton.setText("Remove");
        jRemoveBlockSurfaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveBlockSurfaceButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Select blocks that are");

        jIN_OUT_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inside", "Outside", " " }));

        jLabel15.setText("the surfaces:");

        jSurfaceSelectorComboBoxTOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("and the surface");

        jSurfaceSelectorComboBoxBOTTOM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jAddBlockSurfaceButton1.setText("Add");
        jAddBlockSurfaceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddBlockSurfaceButton1ActionPerformed(evt);
            }
        });

        jRemoveBlockSurfaceButton1.setText("Remove");
        jRemoveBlockSurfaceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveBlockSurfaceButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIN_OUT_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAboveBelowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSurfaceSelectorComboBoxTOP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSurfaceSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddBlockSurfaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoveBlockSurfaceButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSurfaceSelectorComboBoxBOTTOM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddBlockSurfaceButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoveBlockSurfaceButton))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAboveBelowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jSurfaceSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddBlockSurfaceButton)
                    .addComponent(jRemoveBlockSurfaceButton1))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jIN_OUT_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSurfaceSelectorComboBoxTOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jSurfaceSelectorComboBoxBOTTOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddBlockSurfaceButton1)
                    .addComponent(jRemoveBlockSurfaceButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pick Options"));

        jCheckBoxSameX.setText("Same X");

        jCheckBoxSameY.setText("Same Y");
        jCheckBoxSameY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSameYActionPerformed(evt);
            }
        });

        jCheckBoxSameZ.setText("Same Z");

        AddRemoveButtonGroup.add(jRadioButtonPickAdd);
        jRadioButtonPickAdd.setSelected(true);
        jRadioButtonPickAdd.setText("Add");

        AddRemoveButtonGroup.add(jRadioButtonPickRemove);
        jRadioButtonPickRemove.setText("Remove");
        jRadioButtonPickRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPickRemoveActionPerformed(evt);
            }
        });

        jCheckBoxPickSameXY.setText("SameXY (along Z)");
        jCheckBoxPickSameXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPickSameXYActionPerformed(evt);
            }
        });

        jCheckBoxPickSameXZ.setText("SameXZ (along Y)");

        jCheckBoxSameYZ.setText("SameYZ (along X)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPickRemove)
                    .addComponent(jRadioButtonPickAdd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxSameX)
                    .addComponent(jCheckBoxSameZ)
                    .addComponent(jCheckBoxSameY))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPickSameXZ)
                    .addComponent(jCheckBoxSameYZ)
                    .addComponent(jCheckBoxPickSameXY))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPickAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPickRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSameX)
                    .addComponent(jCheckBoxPickSameXY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSameY)
                    .addComponent(jCheckBoxPickSameXZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSameZ)
                    .addComponent(jCheckBoxSameYZ))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jSelectAllVisibleBlocks.setText("Select Visible blocks");
        jSelectAllVisibleBlocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectAllVisibleBlocksActionPerformed(evt);
            }
        });

        jButton3.setText("ResetSelection");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("InvertSelection");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Open Modify Selection...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Genetate INCON");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jSelectAllVisibleBlocks, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4, jSelectAllVisibleBlocks});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSelectAllVisibleBlocks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonClose)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 331, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel4, jPanel5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int value = jComboBox1.getSelectedIndex();
        if (value >= 0) {
            updateformlabels(value);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int value = jComboBox1.getSelectedIndex();
        Tough2Viewer.dataobj.Block_is_selected[value] = false;
        Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model(value);
        update_selected_blocks();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        String searchstring = jTextField1.getText();
        int found = -1;
        for (int i_b = 0; i_b < nxyz; i_b = i_b + 1) {
            if (searchstring.equalsIgnoreCase(Tough2Viewer.dataobj.get_BlockName(i_b))) {
                found = i_b;
                break;
            }

        }
        if (found >= 0) {
            updateformlabels(found);
            Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model();
        } else {
            String error = "Block Name not found!";
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
//        jSurfaceSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
        //      jSurfaceSelectorComboBoxTOP.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
        //    jSurfaceSelectorComboBoxBOTTOM.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jAddRockTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddRockTypeButtonActionPerformed

        //we will search through the block set.
        //if block.rocktype==rocktype, then or we add or we remove...
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        int id_rock = jRockTypeComboBox.getSelectedIndex();
        for (int j = 0; j < nxyz; j++) {
            if (Tough2Viewer.dataobj.get_RockType(j) == id_rock) {
                Tough2Viewer.dataobj.Block_is_selected[j] = true;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.highLightBlock(j, false);
            }
        }
        //updating arraylist:
        update_selected_blocks();
    }//GEN-LAST:event_jAddRockTypeButtonActionPerformed
    public void update_selected_blocks() {

        Tough2Viewer.tough2viewerGUI.VoronoiModel3D.selected_blocks.clear();
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            if (Tough2Viewer.dataobj.Block_is_selected[j]) {
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.selected_blocks.add(j);
            }
        }
    }
    private void jAddBlockSurfaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBlockSurfaceButtonActionPerformed
        //we get the surcaces values....

        int index_surface = jSurfaceSelectorComboBox.getSelectedIndex();
        int mode_above_below = jAboveBelowComboBox.getSelectedIndex();

        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            double tmp_x = Tough2Viewer.dataobj.get_Xo(j);
            double tmp_y = Tough2Viewer.dataobj.get_Yo(j);
            double tmp_z = Tough2Viewer.dataobj.get_Zo(j);
            boolean to_add = false;

            double z_estimated_surface = Tough2Viewer.dataobj.ComputeZ_surface(index_surface, tmp_x, tmp_y, tmp_z);
            if (z_estimated_surface > (-1.0e20)) {
                if (mode_above_below == 0) {
                    if (tmp_z >= z_estimated_surface) {
                        to_add = true;
                    }
                } else if (tmp_z <= z_estimated_surface) {
                    to_add = true;
                }

            }
            if (to_add) {
                Tough2Viewer.dataobj.Block_is_selected[j] = true;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.highLightBlock(j, false);
            }

        }
        update_selected_blocks();
    }//GEN-LAST:event_jAddBlockSurfaceButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PropertyModifier_Jform prop = new PropertyModifier_Jform();
        prop.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jAddBlockSurfaceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddBlockSurfaceButton1ActionPerformed
        int index_surface_top = jSurfaceSelectorComboBoxTOP.getSelectedIndex();
        int index_surface_bottom = jSurfaceSelectorComboBoxBOTTOM.getSelectedIndex();
        int mode_above_in_out = jIN_OUT_ComboBox.getSelectedIndex();
        ArrayList ShapeSurfaces = Tough2Viewer.dataobj.get_ShapesSurface();

        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            double tmp_x = Tough2Viewer.dataobj.get_Xo(j);
            double tmp_y = Tough2Viewer.dataobj.get_Yo(j);
            double tmp_z = Tough2Viewer.dataobj.get_Zo(j);
            boolean to_add = false;

            double z_estimated_surface_TOP = Tough2Viewer.dataobj.ComputeZ_surface(index_surface_top, tmp_x, tmp_y, tmp_z);
            double z_estimated_surface_BOTTOM = Tough2Viewer.dataobj.ComputeZ_surface(index_surface_bottom, tmp_x, tmp_y, tmp_z);
            if (z_estimated_surface_TOP > -1.0e20 && z_estimated_surface_BOTTOM > -1.0e20) {
                if (mode_above_in_out == 0) {
                    if (tmp_z >= z_estimated_surface_BOTTOM && tmp_z < z_estimated_surface_TOP) {
                        to_add = true;
                    }
                } else if (tmp_z <= z_estimated_surface_BOTTOM || tmp_z > z_estimated_surface_TOP) {
                    to_add = true;
                }

            }
            if (to_add) {
                Tough2Viewer.dataobj.Block_is_selected[j] = true;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.highLightBlock(j, false);
            }

        }
        update_selected_blocks();
    }//GEN-LAST:event_jAddBlockSurfaceButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String title = "Clear previous selection confirmation";
        String message = "Clear previous block selection?";

        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            Tough2Viewer.dataobj.set_selectedindex(-1);
            //iTough2Viewer.tough2viewerGUI.VoronoiModel3D.selected_blocks.clear();
            int nxyz = Tough2Viewer.dataobj.get_nxyz();
            for (int j = 0; j < nxyz; j++) {
                Tough2Viewer.dataobj.Block_is_selected[j] = false;
            }
            update_selected_blocks();
            Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model();
        } else {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRockButtonRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRockButtonRemoveButtonActionPerformed
        //we will search through the block set.
        //if block.rocktype==rocktype, then or we add or we remove...
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        int id_rock = jRockTypeComboBox.getSelectedIndex();
        for (int j = 0; j < nxyz; j++) {
            if (Tough2Viewer.dataobj.get_RockType(j) == id_rock) {
                Tough2Viewer.dataobj.Block_is_selected[j] = false;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model(j);
            }
        }
        update_selected_blocks();

    }//GEN-LAST:event_jRockButtonRemoveButtonActionPerformed

    private void jRemoveBlockSurfaceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveBlockSurfaceButton1ActionPerformed
        //we get the surcaces values....

        int index_surface = jSurfaceSelectorComboBox.getSelectedIndex();
        int mode_above_below = jAboveBelowComboBox.getSelectedIndex();
        ArrayList ShapeSurfaces = Tough2Viewer.dataobj.get_ShapesSurface();

        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            double tmp_x = Tough2Viewer.dataobj.get_Xo(j);
            double tmp_y = Tough2Viewer.dataobj.get_Yo(j);
            double tmp_z = Tough2Viewer.dataobj.get_Zo(j);
            boolean to_remove = false;

            double z_estimated_surface = Tough2Viewer.dataobj.ComputeZ_surface(index_surface, tmp_x, tmp_y, tmp_z);
            if (z_estimated_surface > -1.0e20) {
                if (mode_above_below == 0) {
                    if (tmp_z >= z_estimated_surface) {
                        to_remove = true;
                    }
                } else if (tmp_z <= z_estimated_surface) {
                    to_remove = true;
                }

            }
            if (to_remove) {
                Tough2Viewer.dataobj.Block_is_selected[j] = false;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model(j);
            }

        }
        update_selected_blocks();
    }//GEN-LAST:event_jRemoveBlockSurfaceButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            if (Tough2Viewer.dataobj.Block_is_selected[j]) {
                Tough2Viewer.dataobj.Block_is_selected[j] = false;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model(j);
            } else {
                Tough2Viewer.dataobj.Block_is_selected[j] = true;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.highLightBlock(j, false);
            }
        }
        update_selected_blocks();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRemoveBlockSurfaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveBlockSurfaceButtonActionPerformed
        int index_surface_top = jSurfaceSelectorComboBoxTOP.getSelectedIndex();
        int index_surface_bottom = jSurfaceSelectorComboBoxBOTTOM.getSelectedIndex();
        int mode_above_in_out = jIN_OUT_ComboBox.getSelectedIndex();
        ArrayList ShapeSurfaces = Tough2Viewer.dataobj.get_ShapesSurface();

        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            double tmp_x = Tough2Viewer.dataobj.get_Xo(j);
            double tmp_y = Tough2Viewer.dataobj.get_Yo(j);
            double tmp_z = Tough2Viewer.dataobj.get_Zo(j);
            boolean to_remove = false;

            double z_estimated_surface_TOP = Tough2Viewer.dataobj.ComputeZ_surface(index_surface_top, tmp_x, tmp_y, tmp_z);
            double z_estimated_surface_BOTTOM = Tough2Viewer.dataobj.ComputeZ_surface(index_surface_bottom, tmp_x, tmp_y, tmp_z);
            if (z_estimated_surface_TOP > -1.0e20 && z_estimated_surface_BOTTOM > -1.0e20) {
                if (mode_above_in_out == 0) {
                    if (tmp_z >= z_estimated_surface_BOTTOM && tmp_z < z_estimated_surface_TOP) {
                        to_remove = true;
                    }
                } else if (tmp_z <= z_estimated_surface_BOTTOM || tmp_z > z_estimated_surface_TOP) {
                    to_remove = true;
                }

            }
            if (to_remove) {
                Tough2Viewer.dataobj.Block_is_selected[j] = false;
                Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model(j);
            }

        }
        update_selected_blocks();
    }//GEN-LAST:event_jRemoveBlockSurfaceButtonActionPerformed

    private void jSelectAllVisibleBlocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectAllVisibleBlocksActionPerformed
        int nxyz = Tough2Viewer.dataobj.get_nxyz();
        for (int j = 0; j < nxyz; j++) {
            Boolean pippo = Tough2Viewer.tough2viewerGUI.VoronoiModel3D.posMaskBox.get(j);
            if (pippo) {
                Tough2Viewer.dataobj.Block_is_selected[j] = true;
            }
            Tough2Viewer.tough2viewerGUI.VoronoiModel3D.highLightBlock(j, false);
        }
        update_selected_blocks();
    }//GEN-LAST:event_jSelectAllVisibleBlocksActionPerformed

    private void jAddOneBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddOneBlockActionPerformed
        int value = jComboBox1.getSelectedIndex();
        Tough2Viewer.dataobj.Block_is_selected[value] = true;
        Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_model();
        update_selected_blocks();
    }//GEN-LAST:event_jAddOneBlockActionPerformed

    private void jCheckBoxSameYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSameYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSameYActionPerformed

    private void jRadioButtonPickRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPickRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPickRemoveActionPerformed

    private void jCheckBoxPickSameXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPickSameXYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPickSameXYActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jSurfaceSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
        jSurfaceSelectorComboBoxTOP.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
        jSurfaceSelectorComboBoxBOTTOM.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_shapeFileNames()));
        jRockTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_RockType_name_str()));
    }//GEN-LAST:event_formFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (Tough2Viewer.tough2viewerGUI.INCON_Generator_frm != null) {
            Tough2Viewer.tough2viewerGUI.INCON_Generator_frm.setVisible(true);
        } else {
            Tough2Viewer.tough2viewerGUI.INCON_Generator_frm = new INCON_Generator();
            Tough2Viewer.tough2viewerGUI.INCON_Generator_frm.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    void updaterocktype() {
        jRockTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(Tough2Viewer.dataobj.get_RockType_name_str()));
    }

    private void updateformlabels(int value) {
        // TODO add your handling code here:
        Tough2Viewer.dataobj.set_selectedindex(value);
        int actualposition = value;
        // int nxyz=Tough2Viewer.dataobj.get_nxyz();

        if (value >= 0) {
            //jLabel4.setText(Integer.toString(nxyz));
            jLabel6.setText(Tough2Viewer.dataobj.get_BlockName(actualposition));
            jLabel8.setText(Float.toString((Tough2Viewer.dataobj.get_Xo(value))));
            jLabel10.setText(Float.toString((Tough2Viewer.dataobj.get_Yo(value))));
            jLabel12.setText(Float.toString((Tough2Viewer.dataobj.get_Zo(value))));
            int rocktype_n = Tough2Viewer.dataobj.get_RockType(actualposition);
            String rocktype = Tough2Viewer.dataobj.get_RockType_name(rocktype_n);
            jLabel14.setText(rocktype);
        } else {

        }

    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup AddRemoveButtonGroup;
    private javax.swing.JComboBox<String> jAboveBelowComboBox;
    private javax.swing.JButton jAddBlockSurfaceButton;
    private javax.swing.JButton jAddBlockSurfaceButton1;
    private javax.swing.JButton jAddOneBlock;
    private javax.swing.JButton jAddRockTypeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonClose;
    public javax.swing.JCheckBox jCheckBoxPickSameXY;
    public javax.swing.JCheckBox jCheckBoxPickSameXZ;
    public javax.swing.JCheckBox jCheckBoxSameX;
    public javax.swing.JCheckBox jCheckBoxSameY;
    public javax.swing.JCheckBox jCheckBoxSameYZ;
    public javax.swing.JCheckBox jCheckBoxSameZ;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jIN_OUT_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JRadioButton jRadioButtonPickAdd;
    public javax.swing.JRadioButton jRadioButtonPickRemove;
    private javax.swing.JButton jRemoveBlockSurfaceButton;
    private javax.swing.JButton jRemoveBlockSurfaceButton1;
    private javax.swing.JButton jRockButtonRemoveButton;
    private javax.swing.JComboBox<String> jRockTypeComboBox;
    private javax.swing.JButton jSelectAllVisibleBlocks;
    private javax.swing.JComboBox<String> jSurfaceSelectorComboBox;
    private javax.swing.JComboBox<String> jSurfaceSelectorComboBoxBOTTOM;
    private javax.swing.JComboBox<String> jSurfaceSelectorComboBoxTOP;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
