/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tough2ViewerPRJ;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.vecmath.Color3f;
import visad.DisplayRenderer;
import visad.GraphicsModeControl;
import visad.java3d.DisplayImplJ3D;

/**
 *
 * @author stebond
 */
public class IsoSurfaceProperties extends javax.swing.JFrame {

    Color3f Color1 = new Color3f(0f, 1f, 1f);
    Color3f Color2 = new Color3f(0f, 0f, 0f);
    Color3f Color3 = new Color3f(0.7f, .7f, .7f);
    Color3f Color4 = new Color3f(.8f, .8f, .8f);
    IsoSurface3D IsoS3DParent;

    /**
     * Creates new form IsoSurfaceProperties
     */
    public IsoSurfaceProperties(IsoSurface3D IsoS3DParent1) {
        initComponents();
        IsoS3DParent = IsoS3DParent1;
        DisplayRenderer dRenderer = IsoS3DParent.display.getDisplayRenderer();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBackGroundControl = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButtonBoxColor = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IsoSurfaceProperties");

        jButtonBackGroundControl.setText("BackGroundColor");
        jButtonBackGroundControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackGroundControlActionPerformed(evt);
            }
        });

        jButtonBoxColor.setText("BoxColor");
        jButtonBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoxColorActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("BoxVisible");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Perspective");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonBoxColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonBackGroundControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackGroundControl)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBoxColor)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackGroundControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackGroundControlActionPerformed
        Color c = JColorChooser.showDialog(IsoSurfaceProperties.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color1 = new Color3f(r, g, b);

            jTextField3.setForeground(c);
            jTextField3.setBackground(c);
            int i = 1;
            try {
                IsoS3DParent.change_background(Color1);
            } catch (Exception e) {

            }

        } else {

        }

    }//GEN-LAST:event_jButtonBackGroundControlActionPerformed

    private void jButtonBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoxColorActionPerformed
        Color c = JColorChooser.showDialog(IsoSurfaceProperties.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color2 = new Color3f(r, g, b);

            jTextField4.setForeground(c);
            jTextField4.setBackground(c);
            int i = 1;
            try {
                IsoS3DParent.change_boxcolor(Color2);
            } catch (Exception e) {

            }

        } else {

        }

    }//GEN-LAST:event_jButtonBoxColorActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        DisplayRenderer dRenderer = IsoS3DParent.display.getDisplayRenderer();
        if (jCheckBox1.isSelected()) {
            try {
                dRenderer.setBoxOn(true);
            } catch (Exception e) {

            }

        } else {
            try {
                dRenderer.setBoxOn(false);
            } catch (Exception e) {

            }

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        DisplayRenderer dRenderer = IsoS3DParent.display.getDisplayRenderer();
        try {
            GraphicsModeControl dispGMC = (GraphicsModeControl) IsoS3DParent.display.getGraphicsModeControl();
            dispGMC.setScaleEnable(true);
            if (jCheckBox2.isSelected()) {
                dispGMC.setProjectionPolicy(DisplayImplJ3D.PERSPECTIVE_PROJECTION);
            } else {
                dispGMC.setProjectionPolicy(DisplayImplJ3D.PARALLEL_PROJECTION);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible((false));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBackGroundControl;
    private javax.swing.JButton jButtonBoxColor;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
