/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * SurfaceControl.java
 *
 * Created on 2-gen-2011, 20.52.48
 */
package Tough2ViewerPRJ;

import java.awt.Color;
import java.util.ArrayList;
import javax.media.j3d.Appearance;
import javax.media.j3d.Material;
import javax.media.j3d.PolygonAttributes;
import javax.media.j3d.TransparencyAttributes;
import javax.swing.JColorChooser;
import javax.vecmath.Color3f;

/**
 *
 * @author stebond
 */
public class SurfaceControl extends javax.swing.JFrame {

    Color3f Color1 = new Color3f(0f, 1f, 1f);
    Color3f Color2 = new Color3f(0f, 0f, 0f);
    Color3f Color3 = new Color3f(0.7f, .7f, .7f);
    Color3f Color4 = new Color3f(.8f, .8f, .8f);
    int CullFace = PolygonAttributes.CULL_NONE;
    boolean BackFaceNormalFlip = true;
    int PolygonMode = PolygonAttributes.POLYGON_FILL;
    int index;
    PolygonAttributes pa = new PolygonAttributes();

    /**
     * Creates new form SurfaceControl
     */
    public SurfaceControl() {
        initComponents();
        ArrayList ShapeSurfaces = Tough2Viewer.dataobj.Surfaces_Data;
        String[] ShapeFileName = Tough2Viewer.dataobj.get_shapeFileNames2();

        if (ShapeSurfaces.isEmpty()) {
            jButton6.setEnabled(false);
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(ShapeFileName));
        jTextField3.setText("    ");
        jTextField4.setText("    ");
        jTextField5.setText("    ");
        jTextField6.setText("    ");

        Color c = new Color((int) (Color1.x * 255f), (int) (Color1.y * 255f), (int) (Color1.z * 255f));
        jTextField3.setForeground(c);
        jTextField3.setBackground(c);
        c = new Color((int) (Color2.x * 255f), (int) (Color2.y * 255f), (int) (Color2.z * 255f));
        jTextField4.setForeground(c);
        jTextField4.setBackground(c);
        c = new Color((int) (Color3.x * 255f), (int) (Color3.y * 255f), (int) (Color3.z * 255f));
        jTextField5.setForeground(c);
        jTextField5.setBackground(c);
        c = new Color((int) (Color4.x * 255f), (int) (Color4.y * 255f), (int) (Color4.z * 255f));
        jTextField6.setForeground(c);
        jTextField6.setBackground(c);
        update_color(jComboBox1.getSelectedIndex());
        update_advanced(jComboBox1.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonColor1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButtonColor2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButtonColor3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButtonColor4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxBackFace = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCullFace = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPolygonMode = new javax.swing.JComboBox();
        jTextFieldCreaseAngle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SurfaceControl");

        jButton6.setText("Apply");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Select a surface to edit:");

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonColor1.setText("Color1");
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        jButtonColor2.setText("Color2");
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField4");

        jButtonColor3.setText("Color3");
        jButtonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor3ActionPerformed(evt);
            }
        });

        jTextField5.setText("jTextField5");

        jButtonColor4.setText("Color4");
        jButtonColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor4ActionPerformed(evt);
            }
        });

        jTextField6.setText("jTextField6");

        jLabel1.setText("Shininess(0-100)");

        jTextField1.setText("30");

        jLabel2.setText("Transparency (0-1)");

        jTextField2.setText("0.5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonColor1)
                            .addComponent(jButtonColor2)
                            .addComponent(jButtonColor3)
                            .addComponent(jButtonColor4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonColor1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonColor2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonColor3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonColor4)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("App", jPanel1);

        jComboBoxBackFace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True", "False" }));
        jComboBoxBackFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBackFaceActionPerformed(evt);
            }
        });

        jLabel4.setText("setBackFaceNormalFlip");

        jLabel5.setText("setCullFace");

        jComboBoxCullFace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CULL_NONE", "CULL_FRONT", "CULL_BACK", "" }));
        jComboBoxCullFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCullFaceActionPerformed(evt);
            }
        });

        jLabel6.setText("setPolygonMode");

        jComboBoxPolygonMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FILL", "LINE", "POINT" }));
        jComboBoxPolygonMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPolygonModeActionPerformed(evt);
            }
        });

        jTextFieldCreaseAngle.setText("2");

        jLabel7.setText("CreaseAngle");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxBackFace, 0, 51, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxCullFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPolygonMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCreaseAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBackFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCullFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxPolygonMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreaseAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Advanced", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButtonClose))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
        Color c = JColorChooser.showDialog(SurfaceControl.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color1 = new Color3f(r, g, b);
            //jButton1.setBackground(c);
            //jButton1.setForeground(c);
            jTextField3.setForeground(c);
            jTextField3.setBackground(c);
            int i = 1;
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(SurfaceControl.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color2 = new Color3f(r, g, b);
            //jButton2.setBackground(c);
            //jButton2.setForeground(c);
            jTextField4.setForeground(c);
            jTextField4.setBackground(c);
            int i = 1;
        } else {

        }
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButtonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor3ActionPerformed
        Color c = JColorChooser.showDialog(SurfaceControl.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color3 = new Color3f(r, g, b);
            //jButton3.setBackground(c);
            //jButton3.setForeground(c);
            jTextField5.setForeground(c);
            jTextField5.setBackground(c);
            int i = 1;
        } else {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonColor3ActionPerformed

    private void jButtonColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor4ActionPerformed

        Color c = JColorChooser.showDialog(SurfaceControl.this, "Choose a color...", getBackground());
        if (c != null) {
            float r = (float) c.getRed();
            float g = (float) c.getGreen();
            float b = (float) c.getBlue();
            r = r / 255.0f;
            g = g / 255.0f;
            b = b / 255.0f;
            Color4 = new Color3f(r, g, b);
            int i = 1;
            //jButton4.setBackground(c);
            //jButton4.setForeground(c);
            jTextField6.setForeground(c);
            jTextField6.setBackground(c);
        } else {

        }
    }//GEN-LAST:event_jButtonColor4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        float value = Float.parseFloat(jTextField1.getText());
        float Transparency = Float.parseFloat(jTextField2.getText());
        double creaseangle = Double.parseDouble(jTextFieldCreaseAngle.getText());
        pa.setBackFaceNormalFlip(BackFaceNormalFlip);
        pa.setPolygonMode(PolygonMode);
        pa.setCullFace(CullFace);
        Tough2Viewer.tough2viewerGUI.VoronoiModel3D.repaint_shape_surface(index, Color1, Color2, Color3, Color4, value, Transparency, pa);
        Tough2Viewer.tough2viewerGUI.VoronoiModel3D.set_crease_angle(index, creaseangle);
    }//GEN-LAST:event_jButton6ActionPerformed
    private void update_advanced(int index) {
        double creaseangle = Tough2Viewer.tough2viewerGUI.VoronoiModel3D.get_crease_angle(index);
        jTextFieldCreaseAngle.setText(Double.toString(creaseangle));
        pa = Tough2Viewer.tough2viewerGUI.VoronoiModel3D.get_color_surface(index).getPolygonAttributes();
        BackFaceNormalFlip = pa.getBackFaceNormalFlip();
        PolygonMode = pa.getPolygonMode();
        CullFace = pa.getCullFace();
        if (BackFaceNormalFlip) {
            jComboBoxBackFace.setSelectedIndex(0);
        } else {
            jComboBoxBackFace.setSelectedIndex(1);
        }
        if (CullFace == PolygonAttributes.CULL_NONE) {
            jComboBoxCullFace.setSelectedIndex(0);

        } else if (CullFace == PolygonAttributes.CULL_FRONT) {
            jComboBoxCullFace.setSelectedIndex(1);
        } else {
            jComboBoxCullFace.setSelectedIndex(2);
        }

        if (PolygonMode == PolygonAttributes.POLYGON_FILL) {
            jComboBoxPolygonMode.setSelectedIndex(0);

        } else if (PolygonMode == PolygonAttributes.POLYGON_LINE) {
            jComboBoxPolygonMode.setSelectedIndex(1);
        } else {
            jComboBoxPolygonMode.setSelectedIndex(2);
        }

    }

    private void update_color(int index) {
        //qui ci vuole qualcosa che repaint i bottoni del  colore in base all'elemento selezioanto..'
        Appearance myApp = Tough2Viewer.tough2viewerGUI.VoronoiModel3D.get_color_surface(index);
        Material c1 = myApp.getMaterial();
        //Color3f test=new Color3f();

        c1.getDiffuseColor(Color3);
        Color c = new Color(Color3.x, Color3.y, Color3.z);
        jTextField5.setForeground(c);
        jTextField5.setBackground(c);
        //Color3=test;            
        c1.getEmissiveColor(Color2);
        c = new Color(Color2.x, Color2.y, Color2.z);
        jTextField4.setForeground(c);
        jTextField4.setBackground(c);
        //Color2=test;
        c1.getAmbientColor(Color1);
        c = new Color(Color1.x, Color1.y, Color1.z);
        jTextField3.setForeground(c);
        jTextField3.setBackground(c);
        //Color1=test;
        c1.getSpecularColor(Color4);
        c = new Color(Color4.x, Color4.y, Color4.z);
        jTextField6.setForeground(c);
        jTextField6.setBackground(c);
        //Color4=test;
        float shininess = c1.getShininess();
        jTextField1.setText(Float.toString(shininess));
        TransparencyAttributes ta = myApp.getTransparencyAttributes();
        float transparecncy = ta.getTransparency();
        jTextField2.setText(Float.toString(transparecncy));
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        index = jComboBox1.getSelectedIndex();
        update_color(index);
        update_advanced(index);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jComboBoxBackFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBackFaceActionPerformed
        if (jComboBoxBackFace.getSelectedIndex() == 0) {
            BackFaceNormalFlip = true;
        } else {
            BackFaceNormalFlip = false;
        }

    }//GEN-LAST:event_jComboBoxBackFaceActionPerformed

    private void jComboBoxCullFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCullFaceActionPerformed
        if (jComboBoxCullFace.getSelectedIndex() == 0) {
            CullFace = PolygonAttributes.CULL_NONE;
        } else if (jComboBoxCullFace.getSelectedIndex() == 1) {
            CullFace = PolygonAttributes.CULL_FRONT;
        } else {
            CullFace = PolygonAttributes.CULL_BACK;
        }

    }//GEN-LAST:event_jComboBoxCullFaceActionPerformed

    private void jComboBoxPolygonModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPolygonModeActionPerformed
        if (jComboBoxPolygonMode.getSelectedIndex() == 0) {
            PolygonMode = PolygonAttributes.POLYGON_FILL;
        } else if (jComboBoxPolygonMode.getSelectedIndex() == 1) {
            PolygonMode = PolygonAttributes.POLYGON_LINE;
        } else {
            PolygonMode = PolygonAttributes.POLYGON_POINT;
        }
    }//GEN-LAST:event_jComboBoxPolygonModeActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButtonColor4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxBackFace;
    private javax.swing.JComboBox jComboBoxCullFace;
    private javax.swing.JComboBox jComboBoxPolygonMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldCreaseAngle;
    // End of variables declaration//GEN-END:variables

}
